# IN THIS WE WILL PERFORM SETS OF PYTHON WITH DIFFERENT METHODS.

CET={"AMAN","AJAY","NIKITA","SANKET"}
JEE={"ADITI","AJAY","NEHA","SANKET"}
NEET={"AKASH","SOHAM","AJAY","SANKET"}

print(CET & JEE & NEET)
print(CET - JEE - NEET)